version: '2'

services:
  orderer2.example.com:
    container_name: orderer2.example.com
    image: hyperledger/fabric-orderer
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=file
      - ORDERER_GENERAL_BOOTSTRAPFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/example.com/orderers/orderer2.example.com/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/example.com/orderers/orderer2.example.com/tls/:/var/hyperledger/orderer/tls
    ports:
      - 7050:7050
    extra_hosts:
      - "orderer0.example.com:10.0.0.35"
      - "orderer1.example.com:10.0.0.35"
      - "orderer2.example.com:10.0.0.44"
      - "orderer3.example.com:10.0.0.45"
      - "orderer4.example.com:10.0.0.46"
      - "orderer5.example.com:10.0.0.47"
      - "orderer6.example.com:10.0.0.48"
      - "orderer7.example.com:10.0.0.49"
      - "orderer8.example.com:10.0.0.50"
      - "orderer9.example.com:10.0.0.51"
      - "orderer10.example.com:10.0.0.52"

  peer0.org2.example.com:
    container_name: peer0.org2.example.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.org2.example.com
      - CORE_PEER_ADDRESS=peer0.org2.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org2.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.example.com:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Allow more time for chaincode container to build on install.
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
       - /var/run/:/host/var/run/
       - ./crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp:/etc/hyperledger/fabric/msp
       - ./crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
      - 7052:7052
      - 7053:7053
    extra_hosts:
      - "orderer0.example.com:10.0.0.35"
      - "orderer1.example.com:10.0.0.35"
      - "orderer2.example.com:10.0.0.44"
      - "orderer3.example.com:10.0.0.45"
      - "orderer4.example.com:10.0.0.46"
      - "orderer5.example.com:10.0.0.47"
      - "orderer6.example.com:10.0.0.48"
      - "orderer7.example.com:10.0.0.49"
      - "orderer8.example.com:10.0.0.50"
      - "orderer9.example.com:10.0.0.51"
      - "orderer10.example.com:10.0.0.52"

  peer1.org2.example.com:
    container_name: peer1.org2.example.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer1.org2.example.com
      - CORE_PEER_ADDRESS=peer1.org2.example.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org2.example.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org2.example.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.example.com:8051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Allow more time for chaincode container to build on install.
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
       - /var/run/:/host/var/run/
       - ./crypto-config/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/msp:/etc/hyperledger/fabric/msp
       - ./crypto-config/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 8051:8051
      - 8052:8052
      - 8053:8053
    extra_hosts:
      - "orderer0.example.com:10.0.0.35"
      - "orderer1.example.com:10.0.0.35"
      - "orderer2.example.com:10.0.0.44"
      - "orderer3.example.com:10.0.0.45"
      - "orderer4.example.com:10.0.0.46"
      - "orderer5.example.com:10.0.0.47"
      - "orderer6.example.com:10.0.0.48"
      - "orderer7.example.com:10.0.0.49"
      - "orderer8.example.com:10.0.0.50"
      - "orderer9.example.com:10.0.0.51"
      - "orderer10.example.com:10.0.0.52"

  cli1:
    container_name: cli1
    image: hyperledger/fabric-tools
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli1
      - CORE_PEER_ADDRESS=peer0.org2.example.com:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/server.ke
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/go/:/opt/gopath/src/github.com/hyperledger/multiple-deployment/chaincode/go
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    extra_hosts:
      - "orderer0.example.com:10.0.0.35"
      - "orderer1.example.com:10.0.0.35"
      - "orderer2.example.com:10.0.0.44"
      - "orderer3.example.com:10.0.0.45"
      - "orderer4.example.com:10.0.0.46"
      - "orderer5.example.com:10.0.0.47"
      - "orderer6.example.com:10.0.0.48"
      - "orderer7.example.com:10.0.0.49"
      - "orderer8.example.com:10.0.0.50"
      - "orderer9.example.com:10.0.0.51"
      - "orderer10.example.com:10.0.0.52"
      - "peer0.org1.example.com:10.0.0.35"
      - "peer1.org1.example.com:10.0.0.35"
      - "peer0.org2.example.com:10.0.0.44"
      - "peer1.org2.example.com:10.0.0.44"
      - "peer0.org3.example.com:10.0.0.45"
      - "peer1.org3.example.com:10.0.0.45"
      - "peer0.org4.example.com:10.0.0.46"
      - "peer1.org4.example.com:10.0.0.46"
      - "peer0.org5.example.com:10.0.0.47"
      - "peer1.org5.example.com:10.0.0.47"
      - "peer0.org6.example.com:10.0.0.48"
      - "peer1.org6.example.com:10.0.0.48"
      - "peer0.org7.example.com:10.0.0.49"
      - "peer1.org7.example.com:10.0.0.49"
      - "peer0.org8.example.com:10.0.0.50"
      - "peer1.org8.example.com:10.0.0.50"
      - "peer0.org9.example.com:10.0.0.51"
      - "peer1.org9.example.com:10.0.0.51"
      - "peer0.org10.example.com:10.0.0.52"
      - "peer1.org10.example.com:10.0.0.52"

  cli2:
    container_name: cli2
    image: hyperledger/fabric-tools
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli2
      - CORE_PEER_ADDRESS=peer1.org2.example.com:8051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/go/:/opt/gopath/src/github.com/hyperledger/multiple-deployment/chaincode/go
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    extra_hosts:
      - "orderer0.example.com:10.0.0.35"
      - "orderer1.example.com:10.0.0.35"
      - "orderer2.example.com:10.0.0.44"
      - "orderer3.example.com:10.0.0.45"
      - "orderer4.example.com:10.0.0.46"
      - "orderer5.example.com:10.0.0.47"
      - "orderer6.example.com:10.0.0.48"
      - "orderer7.example.com:10.0.0.49"
      - "orderer8.example.com:10.0.0.50"
      - "orderer9.example.com:10.0.0.51"
      - "orderer10.example.com:10.0.0.52"
      - "peer0.org1.example.com:10.0.0.35"
      - "peer1.org1.example.com:10.0.0.35"
      - "peer0.org2.example.com:10.0.0.44"
      - "peer1.org2.example.com:10.0.0.44"
      - "peer0.org3.example.com:10.0.0.45"
      - "peer1.org3.example.com:10.0.0.45"
      - "peer0.org4.example.com:10.0.0.46"
      - "peer1.org4.example.com:10.0.0.46"
      - "peer0.org5.example.com:10.0.0.47"
      - "peer1.org5.example.com:10.0.0.47"
      - "peer0.org6.example.com:10.0.0.48"
      - "peer1.org6.example.com:10.0.0.48"
      - "peer0.org7.example.com:10.0.0.49"
      - "peer1.org7.example.com:10.0.0.49"
      - "peer0.org8.example.com:10.0.0.50"
      - "peer1.org8.example.com:10.0.0.50"
      - "peer0.org9.example.com:10.0.0.51"
      - "peer1.org9.example.com:10.0.0.51"
      - "peer0.org10.example.com:10.0.0.52"
      - "peer1.org10.example.com:10.0.0.52"

